### ISSUE TITLE
Design header and hero banner - Draft

### ISSUE THREAD

**Issue by bhansa** [HydPy/pyconfhyd2022#1]
![image](https://user-images.githubusercontent.com/9723884/190860251-d43694d8-9ead-4ce3-8992-87d0685fa8bd.png)

**Comment by bhansa** [comment]
2.
![image](https://user-images.githubusercontent.com/9723884/191033420-19a6ef0a-3ab0-4664-9186-5d8a203e4142.png)

cc: @ananyo2012

**Comment by ananyo2012** [comment]
@bhansa Shall we update with the 2nd overlay ?

**Comment by bhansa** [comment]
Lets see how it looks with the new logo, I am only concerned about the color contrast.
I have asked @PorwalDhruv05 to come up with a new layout.

**Comment by ananyo2012** [comment]
Let's close this as we will be moving to new background image soon
