### ISSUE TITLE
Design and add Speaker section

### ISSUE THREAD

**Issue by bhansa** [HydPy/pyconfhyd2022#15]
Need to design and add a speaker section on the site. Design should be fluidic and responsive.

**Comment by ananyo2012** [comment]
This is already available now. Just need to uncomment [the code](https://github.com/HydPy/pyconfhyd2022/blob/main/src/pages/speakers.js#L37-L54) and fill the data [here](https://github.com/HydPy/pyconfhyd2022/blob/main/src/data/speakers.yml)

**Comment by ananyo2012** [comment]
Code
