### ISSUE TITLE
Add Footer for website

### ISSUE THREAD

**Issue by bhansa** [HydPy/pyconfhyd2022#16]
Need to design and add footer with logo and links to various sections. 
Previous PyConf site URLS should also be added.

**Comment by abitsalihu** [comment]
Hey @bhansa I would like to help with this issue, I also would like to fix the `Buy tickets` button as the `(coming soon)` part is overflowing atm. :)

**Comment by bhansa** [comment]
Hi @abitsalihu, Thank you for your interest. Please go through the code and feel free to propose a design for footer.
You can also checkout the previous editions of PyConf Hyderabad.

**Comment by abitsalihu** [comment]
@bhansa Alright, can you assign me so I don't lose this ticket

**Comment by abitsalihu** [comment]
@ananyo2012 Hey, please assign someone else on this issue as I am having problems with my terminal and can't even open files atm. Sorry for telling you so late, I have been trying to resolve this for the past 2 days.

**Comment by ananyo2012** [comment]
This is done by @PorwalDhruv05
