### ISSUE TITLE
Add Community Partner on website

### ISSUE THREAD

**Issue by sanghisha145** [HydPy/pyconfhyd2022#49]
Announce community partners on  website with their logos

**Comment by sanghisha145** [comment]
1. [PythonPune]
(Here are the logo files:
https://github.com/pythonpune/design/tree/master/logo/full-logo
SVG (also attached to this email):
https://raw.githubusercontent.com/pythonpune/design/master/logo/vector/PythonPuneLogo.svg
Usage guidelines:
https://github.com/pythonpune/design/wiki/PythonPune-Logo-Usage-Guidelines
)

**Comment by sanghisha145** [comment]
2. [Unlearning-Relearning](https://www.linkedin.com/company/unlearning-relearning/ )

**Comment by sanghisha145** [comment]
3. [Co-learning Lounge]
![co-learning_lounge](https://user-images.githubusercontent.com/5755523/204989171-1061442e-1b4a-4e9a-9e95-9ddb9d4d4462.png)

**Comment by sanghisha145** [comment]
4. Collabnix
![collabnixcomm_logo](https://user-images.githubusercontent.com/5755523/204989122-e424c345-9910-4d75-8bfd-a11401f968f4.png)

**Comment by sanghisha145** [comment]
5. Docker Bangalore
![dockerbangalore_logo](https://user-images.githubusercontent.com/5755523/204989223-b306907d-3da4-4c1d-b0f3-957dfb7e6be3.jpeg)

**Comment by sanghisha145** [comment]
6. GDG Hyderabad
![gdg_hyd](https://user-images.githubusercontent.com/5755523/205021688-82cdd0ee-7c52-4341-845d-a9ad409f282b.png)

**Comment by sanghisha145** [comment]
7. GDG Cloud Hyderabad
![gdg_cloud_hyd](https://user-images.githubusercontent.com/5755523/205021782-43f32318-48b6-4576-b338-d816b9bd1eb5.png)

**Comment by sanghisha145** [comment]
8. GDG Mysuru
![GDG Mysuru Light Horizontal-Logo](https://user-images.githubusercontent.com/5755523/205022189-8f4ac826-b6f7-46d6-a384-437ac5780e66.png)


9. GDG Cloud Mysuru
![GDG Cloud Mysuru Light Horizontal-Logo](https://user-images.githubusercontent.com/5755523/205022304-ee36aaae-6b42-4202-b7fc-e42a90862baf.png)

10. WTM Mysuru
![WTM Mysuru Light Horizontal-Logo](https://user-images.githubusercontent.com/5755523/205022748-b5f6af0d-fb64-4ed8-8b54-affe07707d48.png)

11. TFUG Mysuru
![TFUG Mysuru](https://user-images.githubusercontent.com/5755523/205023161-8c5cdb05-ac40-4d95-99ff-84fb367b799c.png)

**Comment by sanghisha145** [comment]
12. WTM Hyderabad
![WTM Hyd Logo_Original](https://user-images.githubusercontent.com/5755523/205216238-e4d9c0b0-e868-4819-8200-4d3b7d6f56c4.jpeg)

**Comment by sanghisha145** [comment]
13. Meta Developer Circles Hyderabad 
![meta_circles](https://user-images.githubusercontent.com/5755523/205697926-08494b13-a842-45da-a0de-09a38c6ff42c.jpeg)


@bhansa please update this on website

**Comment by bhansa** [comment]
Added.
