### ISSUE TITLE
Add static website generator

### ISSUE THREAD

**Issue by ananyo2012** [HydPy/pyconfhyd2022#5]
Use a suitable static site generator for the code

**Comment by bhansa** [comment]
@dporwal0505 can you check on this one.

**Comment by ananyo2012** [comment]
Please add the suggestions in this issue

**Comment by bhansa** [comment]
- Gatsby (https://www.gatsbyjs.com/docs/quick-start)
- React 
- Preact
- eleventy (https://www.11ty.dev/)

**Comment by bhansa** [comment]
Testing things with **Gatsby**, everything going good till now, https://github.com/bhansa/pyconfhyd2022-gatsby

**Comment by bhansa** [comment]
I am able to get the pipeline working, testing a few things related to paths. Once done, will upgrade the current site with gatsby site.
Build job: https://github.com/bhansa/pyconfhyd2022-gatsby/actions/runs/3182620614/jobs/5214510860

**Comment by ananyo2012** [comment]
@bhansa Is there any deploy preview available ?

**Comment by bhansa** [comment]
This one is for testing: https://bhansa.github.io/hydpy.github.io/2022/

**Comment by ananyo2012** [comment]
Images are not loading. Maybe you can create a PR for this to check the preview

**Comment by bhansa** [comment]
Updated site to gatsby site.
